//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by SERVER1.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDI_QUICK                       102
#define IDI_Jamsa_Press_Logo            103
#define IDI_SOCKET                      105
#define IDI_SOCKMAN                     106
#define IDI_ICON1                       108
#define IDI_WEB                         108
#define IDI_SPIDER                      109
#define ID_SERVER_CLOSE                 32771
#define ID_SERVER_OPEN                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
