// GLOBAL.H
// Global Variables

#include "..\winsock.h"													// Winsock header file
#include "sockman1.h"														// Prototypes and constants

//	Global Sockman variables
extern HWND hwndSockman;												// Sockman window handle
extern HANDLE hInstanceSockman;									// Sockman instance handle
extern char szAppName[9];												// Application name
extern char szPrintBuffer[MAX_PRINT_BUFFER+1];	// Buffer for text to paint

